---
- name: Esure Ansible Facts Dir exists
  file: path=/etc/ansible/facts.d state=directory recurse=yes
  become: yes

- name: Apt-get update
  apt: update_cache=yes
  cache_valid_time: 3600
  become: yes

- name: Install Java
  apt: name=openjdk-8-jdk
  state: present
  become: yes  

