---
- name: Sonar playbook
  hosts: all
  gather_facts: yes
  become: yes
  roles:
     - { role: postgress_db, when: 'inventory_hostname == play_hosts[0]' }
     - { role: sonar, when: 'inventory_hostname == play_hosts[0]' }
     - { role: nexus, when: 'inventory_hostname == play_hosts[1]' }
