---
- name: create conf file
  template:
    src: nginx-conf.j2
    dest: /etc/nginx/sites-available/nginx.conf
  notify:
    - systemd nginx reload
- name: remove default
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
- name: check
  stat:
    path: /etc/nginx/sites-enabled/nginx.conf
  register: result
- name: add link
  file:
    src: /etc/nginx/sites-available/nginx.conf
    dest: /etc/nginx/sites-enabled/nginx.conf
  when: result.stat.exists==false
