---
- name: create  dirs
  file:
    path: '{{ msg_home }}{{ item }}'
    state: directory
    mode: 0755
    owner: '{{ msg_user }}'
    group: '{{ msg_group }}'
  with_items:
    - bin
    - conf
- name: create conf file
  template:
    src: msg-conf.j2
    dest: "{{ destin_file }}"
- name: create unit file
  template:
    src: msg-service.j2
    dest: "{{ destin_unit }}"
  notify:
    - systemd daemon reload
- name: download from url
  get_url: url=https://playpit-labs-assets.s3-eu-west-1.amazonaws.com/msg-service/msg-server dest=/opt/msg-service/bin/  owner={{ msg_user }} group={{ msg_group }} mode=0755
- name: enable application service
  service: name=msg-service enabled=yes
- name: start application service
  service: name=msg-service state=started