---
- name: Create msg dirs
  file:
    path: '{{ app_home }}{{ item }}'
    state: directory
  with_items:
    - bin
    - conf
- name: create conf file
  template:
    src: mysql-check-conf.j2
    dest: "{{ destin_file }}"
- name: create unit file
  template:
    src: mysql-check-service.j2
    dest: "{{ destin_unit }}"
  notify:
    - systemd daemon reload
- name: download from url
  get_url: url=https://playpit-labs-assets.s3-eu-west-1.amazonaws.com/mysql-check/mysql-check dest={{ app_home }}bin/  owner={{ app_user }} group={{ app_group }} mode=0755
- name: cnage ownership
  file:
    path: '{{ app_home }}'
    state: directory
    owner: '{{ app_user }}'
    group: '{{ app_group }}'
    recurse: yes
- name: enable application service
  service: name=mysql_check enabled=yes
- name: start application service
  service: name=mysql_check state=started
