---
- name: Install Java
  apt:
    name: openjdk-8-jdk
    state: present
    update_cache: yes
- name: Create unit file
  template:
    src: nexus.j2
    dest: /etc/systemd/system/nexus.service
  notify:
    - systemd daemon reload
- name: Create  dir
  file:
    path: "{{ nexus_home }}"
    state: directory
    mode: 0755
    owner: "{{ nexus_user }}"
    group: "{{ nexus_group }}"
- name: Unarchive a file that needs to be downloaded (added in 2.0)
  unarchive:
    src: ' https://sonatype-download.global.ssl.fastly.net/repository/repositoryManager/3/nexus-3.16.1-02-unix.tar.gz'
    dest: "{{ nexus_home }}"
    extra_opts: [--strip-components=1]
    remote_src: yes
- name: Recursively change ownership of a directory
  file:
    path: "{{ nexus_home }}"
    state: directory
    recurse: yes
    mode: 0755
    owner: "{{ nexus_user }}"
    group: "{{ nexus_group }}"
- name: Create  dir that this app needs so much
  file:
    path: /opt/sonatype-work
    state: directory
    mode: 0755
    owner: "{{ nexus_user }}"
    group: "{{ nexus_group }}"
- name: enable application service
  service: name=nexus.service state=started enabled=yes